### PR TITLE
 Update DecisionDiffuser Algorithm to omnisafe 

### PR DESCRIPTION
**Pull request by Aidilele**
Update DecisionDiffuser Algorithm to omnisafe

### CODE REVIEW

**Comment by Aidilele** [comment]
Pull from HongyiZhou

**Comment by Gaiejj** [comment]
Thank you for your contribution! We will merge your code following a meticulous code review. 😊

**Comment by LiuTaowen-Tony** [comment]
Hey, I also implemented this algorithm. [here](https://github.com/PKU-Alignment/omnisafe/pull/301)

I mainly implemented actor, algorithm, and dataset. The model architecture is adapted from the original repo.

Maybe we can collaborate a bit

**Comment by Aidilele** [comment]
> Hey, I also implemented this algorithm. [here](https://github.com/PKU-Alignment/omnisafe/pull/301)
> 
> I mainly implemented actor, algorithm, and dataset. The model architecture is adapted from the original repo.
> 
> Maybe we can collaborate a bit

Wow, I'm sorry that I didn't notice your reply. In fact, I am little confuse about the code with condition setting in the original paper. Maybe we can discuss it together.  email -> zhou2429060789@hotmail.com

**Comment by LiuTaowen-Tony** [comment]
> > Hey, I also implemented this algorithm. [here](https://github.com/PKU-Alignment/omnisafe/pull/301)
> > I mainly implemented actor, algorithm, and dataset. The model architecture is adapted from the original repo.
> > Maybe we can collaborate a bit
> 
> Wow, I'm sorry that I didn't notice your reply. In fact, I am little confuse about the code with condition setting in the original paper. Maybe we can discuss it together. email -> [zhou2429060789@hotmail.com](mailto:zhou2429060789@hotmail.com)

Sure, can do. So the author of the original codebase didn't include condition free guidance. I implemented according to the mathematical formula. Please check my pull request, I attached a pdf file explaining the way how I implemented it.

**Pull request closed without merging**
